var Table = require('./js/table');
var data = get_data();
var t = new Table('app',data).sort_by('id');
window.t = t;

function get_data() {
    var jsonO = {
        "title": {
            "id": "编号",
            "name": "姓名",
            "chinese": "语文",
            "math": "数学",
            "english": "英文",
            "medicine": "医学",
            "physical": "物理"
        }, 
        "sortable_title": ["name","chinese", "medicine", "physical"], 
        "sort_mode": ["asc", "desc", "asc"], // 默认升序
        "body": [{
            "id": 0,
            "name": "Jason",
            "chinese": "1",
            "math": "5",
            "english": "1",
            "medicine": "8",
            "physical": "4"
        }, {
            "id": 1,
            "name": "Charles",
            "chinese": "2",
            "math": "2",
            "english": "7",
            "medicine": "5",
            "physical": "9"
        }, {
            "id": 2,
            "name": "Richard",
            "chinese": "7",
            "math": "4",
            "english": "7",
            "medicine": "0",
            "physical": "6"
        }, {
            "id": 3,
            "name": "George",
            "chinese": "9",
            "math": "8",
            "english": "3",
            "medicine": "2",
            "physical": "1"
        }, {
            "id": 4,
            "name": "Matthew",
            "chinese": "2",
            "math": "6",
            "english": "9",
            "medicine": "5",
            "physical": "5"
        }, {
            "id": 5,
            "name": "Larry",
            "chinese": "6",
            "math": "9",
            "english": "9",
            "medicine": "5",
            "physical": "6"
        }, {
            "id": 6,
            "name": "Brian",
            "chinese": "1",
            "math": "0",
            "english": "2",
            "medicine": "9",
            "physical": "9"
        }, {
            "id": 7,
            "name": "Eric",
            "chinese": "2",
            "math": "8",
            "english": "2",
            "medicine": "1",
            "physical": "4"
        }, {
            "id": 8,
            "name": "Timothy",
            "chinese": "4",
            "math": "8",
            "english": "3",
            "medicine": "3",
            "physical": "6"
        }, {
            "id": 9,
            "name": "Anthony",
            "chinese": "0",
            "math": "1",
            "english": "7",
            "medicine": "8",
            "physical": "3"
        }, {
            "id": 10,
            "name": "Matthew",
            "chinese": "5",
            "math": "2",
            "english": "5",
            "medicine": "2",
            "physical": "9"
        }, {
            "id": 11,
            "name": "Christopher",
            "chinese": "4",
            "math": "3",
            "english": "0",
            "medicine": "5",
            "physical": "9"
        }, {
            "id": 12,
            "name": "Charles",
            "chinese": "5",
            "math": "8",
            "english": "2",
            "medicine": "0",
            "physical": "5"
        }, {
            "id": 13,
            "name": "John",
            "chinese": "2",
            "math": "4",
            "english": "2",
            "medicine": "6",
            "physical": "0"
        }, {
            "id": 14,
            "name": "John",
            "chinese": "7",
            "math": "9",
            "english": "3",
            "medicine": "7",
            "physical": "0"
        }, {
            "id": 15,
            "name": "Thomas",
            "chinese": "6",
            "math": "4",
            "english": "8",
            "medicine": "3",
            "physical": "5"
        }]
    };
    return jsonO;
}